# Generated by Django 2.1.1 on 2018-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='imgURL',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imgURL',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
