# Generated by Django 2.1.1 on 2018-09-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0002_auto_20180925_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='imgURL',
            new_name='img_url',
        ),
    ]
