# Generated by Django 2.1.1 on 2018-09-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0003_auto_20180926_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='state',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='location',
            field=models.ManyToManyField(related_name='userLocations', related_query_name='userLocation', to='UCarryout.Location'),
        ),
    ]
