# Generated by Django 2.1.1 on 2018-10-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0005_auto_20180928_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UCarryout.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UCarryout.ClientUser')),
            ],
        ),
    ]
