# Generated by Django 2.1.1 on 2018-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0006_customerpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('img_url', models.CharField(max_length=150)),
                ('bonus_points', models.IntegerField()),
                ('requirements', models.CharField(max_length=150)),
                ('valid_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='active_promotion',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='UCarryout.Promotion'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='promotions',
            field=models.ManyToManyField(related_name='promotions', related_query_name='promotion', to='UCarryout.Promotion'),
        ),
    ]
