# Generated by Django 2.1.1 on 2018-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0007_auto_20181016_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='active_promotion',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='active_promotions',
            field=models.ManyToManyField(related_name='active_promotions', related_query_name='active_promotion', to='UCarryout.Promotion'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='items_purchased',
            field=models.ManyToManyField(related_name='item_purchased', related_query_name='items_purchased', to='UCarryout.Food'),
        ),
    ]
