# Generated by Django 2.1.1 on 2018-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCarryout', '0008_auto_20181020_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='fav_restaurants',
            field=models.ManyToManyField(related_name='fav_restaurants', related_query_name='fav_restaurant', to='UCarryout.Restaurant'),
        ),
    ]
